#!/usr/bin/env -S uv run python
import json
import os
from pathlib import Path

workflow = Path(os.environ["CONTROL_TOWER_WORKFLOW"])
data = workflow / "data"
(data / "record.json").unlink(missing_ok=True)
