#!/usr/bin/env -S uv run python
import os
from pathlib import Path
workflow = Path(os.environ["CONTROL_TOWER_WORKFLOW"])
data = workflow / "data"
(data / "tool_result.json").unlink(missing_ok=True)
(data / "runtime_context.json").unlink(missing_ok=True)
