#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
if (fs.existsSync(path.join(process.env.CONTROL_TOWER_WORKSPACE, "data", "node_inspection.json"))) {
  throw new Error("node_inspection.json still exists after reversal");
}
